tasks:
  - type: docker-build
    image: hestia
    auto:
      - source: push
        has_tag: true
        tag_source: tag
      - source: push
        has_tag: true
        tag_source: latest
    context: .
    file: Dockerfile
    registries:
      - gitlab
      # - docker-hub
    labels:
      source: https://gitlab.com/haondt/hestia
      url: https://docs.haondt.dev/talaria/
      title: hestia
      image.base.name: mcr.microsoft.com/dotnet/aspnet:9.0
